---
title: "OMAP_MSanalysis"
author: "Andrew Dominguez"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r Import .tsv data}
library(readr)

#PC Working Directory
#wd <- setwd("C:/Users/anmdo/Desktop/Analysis_Wkspce/archive_2024_05_15__15_13_08/20240515_1239_dominiquez/") 

#Mac Working Directory
wd <- setwd("/Users/andrewd/Desktop/Analysis_wkspce/OMAP_proteomics") 


dataImport <- readr::read_tsv("Candidates.tsv")
Comparisons <- unique(dataImport$`Comparison (group1/group2)`)
Comparisons

```

```{r remove non-yeast contaminates and append GO terms}
library(tidyverse)
yeastSubset <- dataImport %>% filter(Organisms == "Saccharomyces cerevisiae (strain ATCC 204508 / S288c)")


```

```{r subset on valid comparisons}
DataSubset <- function(Subset) {
  SubsetDF <- subset(yeastSubset, yeastSubset$`Comparison (group1/group2)`== Subset) #input subset here: "ITS2 FLX" 
  SubsetValues <- dplyr::select(SubsetDF,`Comparison (group1/group2)`, Group, `AVG Group Quantity Numerator`, 
                                `AVG Group Quantity Denominator`, `AVG Log2 Ratio`, Ratio, ProteinGroups, 
                                ProteinNames, ProteinDescriptions, Genes, UniProtIds, Organisms,`Protein Coverage`,
                                `Molecular Weight`, `# Unique Total Peptides`, `# Unique Total EG.Id`)
  SubsetValues <- SubsetValues[order(SubsetValues$`AVG Log2 Ratio`),]
  return(SubsetValues)
}
# colList <- colnames(DataSubset)
# colList
```

```{r}
#Comparison subsets 
Pierce_dTvITS2 <- DataSubset("dT-Pierce / ITS2-Pierce")
Pierce_ScrvITS2 <- DataSubset("Scramble-Pierce / ITS2-Pierce")
Pierce_ScrvdT <- DataSubset("Scramble-Pierce / dT-Pierce")
ITS2_DynavPierce <- DataSubset("ITS2-Dyna / ITS2-Pierce")
ITS2_DynavPierce <- DataSubset("dT-Dyna / dT-Pierce")
Dyna_dTvITS2 <- DataSubset("dT-Dyna / ITS2-Dyna")
table(unlist(yeastSubset$`Comparison (group1/group2)`))

```



```{r}
library(clusterProfiler)
library(org.Sc.sgd.db)
library(AnnotationDbi)
library(patchwork)
library(enrichplot)
library(svglite)
library(ggrepel)
library(plotly)


UniprotData <- data.frame(org.Sc.sgdUNIPROT)
ensemblData <- data.frame(org.Sc.sgdENSEMBL2ORF)
MergeMeta <- merge(UniprotData, ensemblData, by = "systematic_name")

GO_call_denom <- function(Subset, Annotation) {
  EnrichedGenes <- Subset[Subset$`AVG Log2 Ratio` < -1, ]
  GO_annotation <- data.frame(EnrichedGenes$UniProtIds) %>% na.omit() 
  names(GO_annotation)[1]<-paste("uniprot_id")
  GO_annotation <- merge(GO_annotation, MergeMeta, by = "uniprot_id")
  GO_Results <- enrichGO(gene = GO_annotation$ensembl_id, OrgDb = "org.Sc.sgd.db", keyType = "ENSEMBL", ont = Annotation)
  #GO_Results <- data.frame(GO_Results)
  return(GO_Results)
}


GO_call_numer <- function(Subset, Annotation) {
  EnrichedGenes <- Subset[Subset$`AVG Log2 Ratio` > 1, ]
  GO_annotation <- data.frame(EnrichedGenes$UniProtIds) %>% na.omit() 
  names(GO_annotation)[1]<-paste("uniprot_id")
  GO_annotation <- merge(GO_annotation, MergeMeta, by = "uniprot_id")
  GO_Results <- enrichGO(gene = GO_annotation$ensembl_id, OrgDb = "org.Sc.sgd.db", keyType = "ENSEMBL", ont = Annotation)
  #GO_Results <- data.frame(GO_Results)
  return(GO_Results)
}

GO_Plot <- function(Data){
  GO_plot <- plot(barplot(Data, showCategory = 20))
  return(GO_plot)  
}


GOIs <-function(data){
  GeneSubset <- subset(data, 
                       Genes == "NOP7" | 
                       Genes == "ERB1" | 
                       Genes == "YTM1" | 
                       Genes == "NAB2" |
                       Genes == "PAB1" |
                       Genes == "DBP5" |
                       Genes == "THO2" |
                       Genes == "CTK1" |
                       Genes == "YRA1" |
                       Genes == "CDC33") #translation initiation factor eIF4E
  return(GeneSubset)
  
} 
```

```{r identify and regress out Scramble enriched genes}

ScrambleEnrich_dT <- subset(Pierce_ScrvdT, `AVG Log2 Ratio` > 0)
ScrambleEnrich_ITS2 <- subset(Pierce_ScrvITS2, `AVG Log2 Ratio` > 0)
ScrambleEnriched <- merge(ScrambleEnrich_dT, ScrambleEnrich_ITS2, by = "Genes")
Pierce_dTvITS2_noScr <- anti_join(Pierce_dTvITS2, ScrambleEnriched, by = "Genes")

```



```{r}
#ITS2 and dT verses scramble

Annotation_Param <- "CC" # GO annotations: biological process (BP), Cellular Component (CC), Molecular Function (MF)
GO_Pierce_ITS2 <- GO_call_denom(Pierce_ScrvITS2, Annotation_Param)
GO_Pierce_ScrITS2 <- GO_call_numer(Pierce_ScrvITS2, Annotation_Param)

GO_Pierce_dT <- GO_call_denom(Pierce_ScrvdT, Annotation_Param)
GO_Pierce_ScrdT <- GO_call_numer(Pierce_ScrvdT, Annotation_Param)

#ITS2 vs dT using Pierce beads
GO_ITS2_Pierce_dTvITS2 <- GO_call_denom(Pierce_dTvITS2, Annotation_Param)
GO_dT_Pierce_dTvITS2 <- GO_call_numer(Pierce_dTvITS2, Annotation_Param)

#ITS2 vs dT using Pierce beads (Scr regressed out)
GO_ITS2_Pierce_dTvITS2_NoScr <- GO_call_denom(Pierce_dTvITS2_noScr, Annotation_Param)
GO_dT_Pierce_dTvITS2_NoScr <- GO_call_numer(Pierce_dTvITS2_noScr, Annotation_Param)

#ITS2 vs dT using Dynabeads
GO_ITS2_Dyna_dTvITS2 <- GO_call_denom(Dyna_dTvITS2, Annotation_Param)
GO_dT_Dyna_dTvITS2 <- GO_call_numer(Dyna_dTvITS2, Annotation_Param)

#ITS2 Pierce vs Dynabeads
#GO_ITS2_Pierce <- GO_call_denom(ITS2_DynavPierce)
#GO_ITS2_Dyna <- GO_call_numer(ITS2_DynavPierce)

#dT Pierce vs Dynabeads
#GO_dT_Pierce <- GO_call_denom(ITS2_DynavPierce)
#GO_dT_Dyna <- GO_call_numer(ITS2_DynavPierce)

```


```{r Results from ITS2 enriched genes from scramble}

GOI_subset <- GOIs(Pierce_ScrvITS2)
DistPlot <- ggplot(data=Pierce_ScrvITS2, aes(x=`AVG Group Quantity Denominator`, y=`AVG Group Quantity Numerator`)) + 
  geom_point(alpha = 0.1) +
  coord_cartesian(xlim = c(0, 500), ylim = c(0, 500)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(data = Pierce_ScrvITS2 %>% filter(`AVG Log2 Ratio` > 1), color = "darkorange", alpha = 0.75) +
  geom_point(data = Pierce_ScrvITS2 %>% filter(`AVG Log2 Ratio` < -1), color = "dodgerblue3", alpha = 0.75) +
  ggtitle("Relative protein abundance between samples") +
  xlab("Count in ITS2-sample") + ylab("Count in Scramble-sample") +
  geom_point(data = GOI_subset, color = "darkorchid", alpha = 1) +
  geom_text_repel(data = GOI_subset,
                  aes(label = Genes),
                  size = 3,
                  box.padding = unit(1, "lines"),
                  point.padding = unit(0.5, "lines"),
                  min.segment.length = unit(0, 'lines'))
DistPlot
UpsetGO <- plot_spacer() + upsetplot(GO_Pierce_ITS2)

ggsave("ITS2vScr_Dist.png", plot = DistPlot, scale = 1, width = 2000, height = 2000, units = "px", dpi = 300)
ggsave("ITS2vScr_GO.png", plot = UpsetGO, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```








```{r Results from dT enriched genes from scramble}

GOI_subset <- GOIs(Pierce_ScrvdT)
DistPlot <- ggplot(data=Pierce_ScrvdT, aes(x=`AVG Group Quantity Denominator`, y=`AVG Group Quantity Numerator`)) + 
  geom_point(alpha = 0.1) +
  coord_cartesian(xlim = c(0, 250), ylim = c(0, 250)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(data = Pierce_ScrvdT %>% filter(`AVG Log2 Ratio` > 1), color = "darkorange", alpha = 0.75) +
  geom_point(data = Pierce_ScrvdT %>% filter(`AVG Log2 Ratio` < -1), color = "dodgerblue3", alpha = 0.75) +
  ggtitle("Relative protein abundance between samples") +
  xlab("Count in dT-sample") + ylab("Count in Scramble-sample") +
  geom_point(data = GOI_subset, color = "darkorchid", alpha = 1) +
  geom_text_repel(data = GOI_subset,
                  aes(label = Genes),
                  size = 3,
                  box.padding = unit(1, "lines"),
                  point.padding = unit(0.5, "lines"),
                  min.segment.length = unit(0, 'lines'))
  
DistPlot
UpsetGO <- plot_spacer() + upsetplot(GO_Pierce_dT)


ggsave("dTvScr_Dist.png", plot = DistPlot, scale = 1, width = 2000, height = 2000, units = "px", dpi = 300)
ggsave("dTvScr_GO.png", plot = UpsetGO, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```



```{r Results from ITS2 enriched genes from dT (Pierce beads)}

GOI_subset <- GOIs(Pierce_dTvITS2)
DistPlot <- ggplot(data=Pierce_dTvITS2, aes(x=`AVG Group Quantity Denominator`, y=`AVG Group Quantity Numerator`)) + 
  geom_point(alpha = 0.1) +
  coord_cartesian(xlim = c(0, 500), ylim = c(0, 500)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(data = Pierce_dTvITS2 %>% filter(`AVG Log2 Ratio` > 1), color = "darkorange", alpha = 0.75) +
  geom_point(data = Pierce_dTvITS2 %>% filter(`AVG Log2 Ratio` < -1), color = "dodgerblue3", alpha = 0.75) +
  ggtitle("Relative protein abundance between samples") +
  xlab("Count in ITS2-sample") + ylab("Count in dT-sample") +
  geom_point(data = GOI_subset, color = "darkorchid", alpha = 1) +
  geom_text_repel(data = GOI_subset,
                  aes(label = Genes),
                  size = 3,
                  box.padding = unit(1, "lines"),
                  point.padding = unit(0.5, "lines"),
                  min.segment.length = unit(0, 'lines'))
DistPlot
UpsetGO <-  upsetplot(GO_ITS2_Pierce_dTvITS2) #may need to make use of "plot_spacer() +"

ggsave("ITS2vdT_Pierce_Dist.png", plot = DistPlot, scale = 1, width = 2000, height = 2000, units = "px", dpi = 300)
ggsave("ITS2vdT_Pierce_GO.png", plot = UpsetGO, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```

```{r Results from ITS2 enriched genes from dT (Scr genes removed)}

GOI_subset <- GOIs(Pierce_dTvITS2_noScr)
DistPlot <- ggplot(data=Pierce_dTvITS2_noScr, aes(x=`AVG Group Quantity Denominator`, y=`AVG Group Quantity Numerator`)) + 
  geom_point(alpha = 0.1) +
  coord_cartesian(xlim = c(0, 500), ylim = c(0, 500)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(data = Pierce_dTvITS2 %>% filter(`AVG Log2 Ratio` > 1), color = "darkorange", alpha = 0.75) +
  geom_point(data = Pierce_dTvITS2 %>% filter(`AVG Log2 Ratio` < -1), color = "dodgerblue3", alpha = 0.75) +
  ggtitle("Relative protein abundance between samples") +
  xlab("Count in ITS2-sample") + ylab("Count in dT-sample") +
  geom_point(data = GOI_subset, color = "darkorchid", alpha = 1) +
  geom_text_repel(data = GOI_subset,
                  aes(label = Genes),
                  size = 3,
                  box.padding = unit(1, "lines"),
                  point.padding = unit(0.5, "lines"),
                  min.segment.length = unit(0, 'lines'))
DistPlot
UpsetGO <-  upsetplot(GO_ITS2_Pierce_dTvITS2_NoScr) #may need to make use of "plot_spacer() +"

ggsave("ITS2vdT_Pierce_Dist_noScr.png", plot = DistPlot, scale = 1, width = 2000, height = 2000, units = "px", dpi = 300)
ggsave("ITS2vdT_Pierce_GO_noScr.png", plot = UpsetGO, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```



```{r Results from dT enriched genes from ITS2 (Pierce beads)}

UpsetGO <- plot_spacer() + upsetplot(GO_dT_Pierce_dTvITS2)
ggsave("dTvITS2_Pierce_GO.png", plot = UpsetGO, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```

```{r Results from ITS2 enriched genes from dT (Dyna beads)}

GOI_subset <- GOIs(Dyna_dTvITS2)
DistPlot <- ggplot(data=Dyna_dTvITS2, aes(x=`AVG Group Quantity Denominator`, y=`AVG Group Quantity Numerator`)) + 
  geom_point(alpha = 0.1) +
  coord_cartesian(xlim = c(0, 500), ylim = c(0, 500)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point(data = Dyna_dTvITS2 %>% filter(`AVG Log2 Ratio` > 1), color = "darkorange", alpha = 0.75) +
  geom_point(data = Dyna_dTvITS2 %>% filter(`AVG Log2 Ratio` < -1), color = "dodgerblue3", alpha = 0.75) +
  ggtitle("Relative protein abundance between samples (Dynabeads)") +
  xlab("Count in ITS2-sample") + ylab("Count in dT-sample") +
  geom_point(data = GOI_subset, color = "darkorchid", alpha = 1) +
  geom_text_repel(data = GOI_subset,
                  aes(label = Genes),
                  size = 3,
                  box.padding = unit(1, "lines"),
                  point.padding = unit(0.5, "lines"),
                  min.segment.length = unit(0, 'lines'))

DistPlot
UpsetGO_ITS2 <- plot_spacer() + upsetplot(GO_ITS2_Dyna_dTvITS2)
#UpsetGO_dT <- plot_spacer() + upsetplot(GO_dT_Dyna_dTvITS2) No enrichment from dynabeads

ggsave("ITS2vdT_Dyna_Dist.png", plot = DistPlot, scale = 1, width = 2000, height = 2000, units = "px", dpi = 300)
ggsave("ITS2_Dyna_GO.png", plot = UpsetGO_ITS2, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
#ggsave("dT_Dyna_GO.png", plot = UpsetGO_dT, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```

```{r}
library(org.Sc.sgd.db)
library(ggVennDiagram)

retrieved <- AnnotationDbi::select(org.Sc.sgd.db, keytype="GOALL", keys="GO:0005730", columns="ENSEMBL") 
retrieved <- na.omit(retrieved)
retrievedList <- unique(retrieved$ENSEMBL)

hits <- Pierce_dTvITS2_noScr %>% filter(`AVG Log2 Ratio` < -1)
hits <- data.frame(hits$UniProtIds)
names(hits)[1] <- "uniprot_id"
hits <- merge(hits, MergeMeta, by = "uniprot_id" )
names(hits)[3] <- "ENSEMBL"
NonNucleolarProts <- data.frame(anti_join(hits, retrieved, by="ENSEMBL"))

NonNucleolarGO <- enrichGO(gene = NonNucleolarProts$ENSEMBL, OrgDb = "org.Sc.sgd.db", keyType = "ENSEMBL", ont = "CC")



NucleolarVenn <- ggVennDiagram(list(hits$ENSEMBL, retrievedList),
                               color = "black",
                               label = "count",
                               category.names = c("ITS2 OMAP","Nucleolar Prots")) +
  theme(legend.position = "none") +
  scale_fill_gradient(low = "#F4FAFE", high = "#F4FAFE") +
  scale_x_continuous(expand = expansion(mult = .5)) 



PlotMerge <-  NucleolarVenn + upsetplot(NonNucleolarGO)

ggsave("Nucleolar_OL.png", plot = PlotMerge, scale = 1, width = 3000, height = 2000, units = "px", dpi = 300)
```




```{bash}
rm *.log
mkdir outputs/
mv *.png outputs/ 
```

